version: 2
jobs:
  test-node8:
    docker:
      - image: node:8
    working_directory: ~/redux-promise-inspections
    steps:
      - checkout
      - restore_cache:
          key: dependencies-node8-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-node8-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn build

  test-node10:
    docker:
      - image: node:10
    working_directory: ~/redux-promise-inspections
    steps:
      - checkout
      - restore_cache:
          key: dependencies-node10-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-node10-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn build

  test-node12:
    docker:
      - image: node:12
    working_directory: ~/redux-promise-inspections
    steps:
      - checkout
      - restore_cache:
          key: dependencies-node12-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-node12-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn build

  deploy:
    docker:
      - image: node:12
    working_directory: ~/redux-promise-inspections
    steps:
      - checkout
      - restore_cache:
          key: dependencies-node12-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run:
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --unsafe-perm

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test-node8:
          filters:
            tags:
              only: /.*/
      - test-node10:
          filters:
            tags:
              only: /.*/
      - test-node12:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test-node8
            - test-node10
            - test-node12
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
